### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by JeffGuKang** [JeffGuKang/npm-webpack-boilerplate#29]
Need to add `report` folder made by test script to .gitignore. 

test 스크립트로 생기는 `report` 폴더가 .gitignore에 추가되어야 합니다. 
아직 풀리퀘스트 안해보신분이 해주세요.

**Comment by lacieliz** [comment]
https://github.com/JeffGuKang/npm-webpack-boilerplate/pull/31
추가했습니다.
