### ISSUE TITLE
Karma 테스트 bug

### ISSUE THREAD

**Issue by nygosh** [JeffGuKang/npm-webpack-boilerplate#30]
현재 Karma test중 browser설치가 안되어 있는 경우 버그발생(제 경우 FireFox가 미설치)
크롬이나 파이어폭스 미설치시 오류 발생할것으로 예상됩니다.

1. 브라우져 예외처리가 가능한가요?(기본 설치되어 있는 브라우져로 실행)

2. 브라우져 선택하여 실행 가능한가요?

![11](https://cloud.githubusercontent.com/assets/22047220/18856040/9552e934-8492-11e6-810c-5645db266d68.PNG)

**Comment by MuhunKim** [comment]
```console
26 09 2016 23:23:22.345:INFO [launcher]: Starting browser Chrome
26 09 2016 23:23:22.354:ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
26 09 2016 23:23:22.372:INFO [launcher]: Starting browser PhantomJS
26 09 2016 23:23:22.677:INFO [launcher]: Starting browser Firefox
26 09 2016 23:23:22.937:ERROR [phantomjs.launcher]: /mnt/c/Users/Kim/Desktop/npm-module-es2015-boilerplate/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

26 09 2016 23:23:23.037:ERROR [launcher]: Cannot start PhantomJS
```
흠,, 전 크롬이 설치되어있는데도 그러네요.

**Comment by nygosh** [comment]
"CHROME_BIN" 환경변수를 못찾는다고 하는거보니,
ios에선 크롬사용할때 환경변수 따로 셋팅하나요??(mac을 사용안해봐서....)
아래 PhantomJS에서도 애러가 나네요....

**Comment by MuhunKim** [comment]
```console
SET CHROME_BIN = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
```
윈도우인 경우는 환경변수를 [이렇게 잡으라고 하는데](http://stackoverflow.com/questions/16017896/setting-environment-variable-for-chrome-bin-does-not-work) 맥은 따로 설정하셔야 될것 같네요.

**Comment by nygosh** [comment]
@MuhunKim  아직 미설치시 버그는 해결 안된 것 같습니다. Closed는 어떻게 수정 할 수 있나요??

**Comment by JeffGuKang** [comment]
@nygosh iOS에서도 크롬사용시 따로 환경변수를 건드리진 않습니다

**Comment by ohdoking** [comment]
앗 그래요 흠... 그럼...... !!! phantomjs만 가도 괜찮을까요 따로 에러처리를 할수잇는게 안보여서요...

**Comment by nygosh** [comment]
@MuhunKim 님 로그보면 
26 09 2016 23:23:22.937:ERROR [phantomjs.launcher]: /mnt/c/Users/Kim/Desktop/npm-module-es2015-boilerplate/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

26 09 2016 23:23:23.037:ERROR [launcher]: Cannot start PhantomJS

PhantomJS로 애러나는거 아닌가요??

**Comment by MuhunKim** [comment]
`SET CHROME_BIN = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`
환경변수를 크롬의 디렉터리에 잡으니까 잘됩니다.
```console
27 09 2016 11:30:01.009:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
27 09 2016 11:30:01.013:INFO [launcher]: Launching browsers Chrome, PhantomJS, Firefox with unlimited concurrency
27 09 2016 11:30:01.045:INFO [launcher]: Starting browser Chrome
27 09 2016 11:30:01.061:INFO [launcher]: Starting browser PhantomJS
27 09 2016 11:30:01.105:INFO [launcher]: Starting browser Firefox
27 09 2016 11:30:02.913:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on socket /#jkgQ_n17cLIiS6HxAAAA with id 40917491
27 09 2016 11:30:03.865:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#FRWN5MsS_P8LpvWgAAAB with id 86660610
27 09 2016 11:31:01.107:WARN [launcher]: Firefox have not captured in 60000 ms, killing.
27 09 2016 11:31:03.111:WARN [launcher]: Firefox was not killed in 2000 ms, sending SIGKILL.
27 09 2016 11:31:05.115:WARN [launcher]: Firefox was not killed by SIGKILL in 2000 ms, continuing.
```

**Comment by ohdoking** [comment]
전 디렉토리를 잡지않아도 잘됫는데 왜그럴까요 ?! 후 정확한 원인을 알수가없네요 ㅎㅎ 
테스트 환경은 os x el capitan이였습니다. 

윈도우도 다시 제 노트북으로 테스트해볼게요 ㅎㅎ

**Comment by MuhunKim** [comment]
close

**Comment by MuhunKim** [comment]
@nygosh 콘솔 로그 적으실때 마크다운 문법을 활용하시면 보기 편합니다.
### ex)
\`\`\`console
$ python
\`\`\`

**Comment by nygosh** [comment]
@MuhunKim  좋은 팁 감사합니다^^ 아직 마크다운 문법이 숙달 되지않아서ㅎㅎ

**Comment by JeffGuKang** [comment]
윈도우쪽은 환경변수 이슈가 있나보네요 :) 사용법에 추가해도 좋을거 같습니다.

**Comment by nygosh** [comment]
처음 발견한 버그는 FireFox가 설치 안되었을 경우에 발생되는 오류로 아직 해결이 안된 상태입니다.

**Comment by JeffGuKang** [comment]
@nygosh 
일단 기본적으로 `karma.conf.js`에서  17번째 줄인  
```
browsers: ['Chrome','PhantomJS','Firefox'],
```
부분을 수정하면 됩니다.
