### ISSUE TITLE
Rearrangement files and Delete example folder

### ISSUE THREAD

**Issue by choseungyoon** [JeffGuKang/npm-webpack-boilerplate#32]
Delete example folder and rearrangement calculator file to src.
And check and change each filename.

Example 폴더를 삭제하고, 내부 파일은 src 파일로 옮길거 같아요.
그리고 filename 을 체크한번 할게요!
@ohdoking

**Comment by MuhunKim** [comment]
@choseungyoon 그럼 예제 코드들은 어디로 이동하나요?

**Comment by JeffGuKang** [comment]
#26  Applied.

**Comment by choseungyoon** [comment]
@MuhunKim  예제 코드는 src 폴더에 exampleModule.js 파일로 옮겼고, 곧 exampleModule.js 파일이름도 calculator.js로 수정할 예정입니다.

**Comment by TylorShin** [comment]
Example에 Module 이름과 Contributors 같은 거 README.MD 처럼 올리는 것도 나쁘진 않을 거 같아요

**Comment by ohdoking** [comment]
감사합니다~

**Comment by JeffGuKang** [comment]
Calculator-test.js -> calculatorTest.js  로 바꾸는게 날까요?

**Comment by choseungyoon** [comment]
@JeffGuKang  아 그게 좋을거같네요. 반영할게요!

**Comment by choseungyoon** [comment]
@JeffGuKang  파일이름 수정해서 PR보냈습니다.

**Comment by JeffGuKang** [comment]
@choseungyoon 파일이름 수정은 README와 다른 브런치에서 처리해주세요 :)

**Comment by choseungyoon** [comment]
@JeffGuKang 
브런치 나누고 파일이름 및 경로 수정하고 PR 보냈습니다.
잘 실행되었는지 확인까지 했습니다.
